# NumPy

- Ele é a "base" para o Pandas
<br><br>
- Numerical Python
    - Biblioteca de computação numérica
    - Otimizada para cálculos pesados
- https://numpy.org/
<br><br>
- No NumPy vamos trabalhar com <font color="blue">**arrays**</font>, que são mais rápidos e mais performáticos que listas

In [1]:
# Importar o numpy

import numpy as np

### A importância do NumPy

#### Vamos supor que temos a venda e comissão (em percentual) de 5 vendedores e queremos saber qual vai ser o salário de cada um deles

In [2]:
# Venda e comissão
venda_valor = [150000,230000,82000,143000,184000]
comissao = [5,8,8,5,12]

In [3]:
type(venda_valor)

list

In [4]:
# Ao tentar fazer essa operação com listas, teremos um erro
venda_valor*(comissao/100)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

### Transformar uma lista em um array:

meu_array = <font color="blue">**np.array**</font>(minha_lista)

In [ ]:
# Transformando em um array
venda_valor_array = np.array(venda_valor)
comissao_array = np.array(comissao)

In [ ]:
# Agora vamos conseguir fazer sendo um array
venda_valor_array*(comissao_array/100)

array([ 7500., 18400.,  6560.,  7150., 22080.])

### Dimensões de um array

meu_array<font color="blue">**.shape**</font>

In [ ]:
print(venda_valor_array)

[150000 230000  82000 143000 184000]


In [ ]:
venda_valor_array.shape

(5,)

##### Todos os dados de um array vão ter o mesmo tipo

Para saber o tipo dos dados, podemos fazer: <br>
meu_array<font color="blue">**.dtype**</font>

In [ ]:
venda_valor_array.dtype

dtype('int32')

##### Se tiver dados de diferentes tipos, ele converte para o mesmo tipo

In [ ]:
tipos_dados = np.array([1,2,3,4,5])
print(tipos_dados)
tipos_dados.dtype

[1 2 3 4 5]


dtype('int32')

In [5]:
tipos_dados = np.array([1,2,3,4.5,5])
print(tipos_dados.dtype)
print(tipos_dados)

float64
[1.  2.  3.  4.5 5. ]


In [ ]:
tipos_dados = np.array([1,2,3,'4',5])
print(tipos_dados.dtype)
print(tipos_dados)

<U11
['1' '2' '3' '4' '5']


### O array de uma dimensão é o que chamamos de vetor e o de duas dimensões de matriz

In [ ]:
dados_venda = np.array([[150000,230000,82000,143000,184000],[5,8,8,5,12]])

In [ ]:
print(dados_venda)

[[150000 230000  82000 143000 184000]
 [     5      8      8      5     12]]


In [ ]:
dados_venda.shape

(2, 5)

In [ ]:
dados_venda.dtype

dtype('int32')

In [ ]:
dados_venda = np.array([['Lucas','Bia','Jean','Gabi','Pedro'],[150000,230000,82000,143000,184000]])
print(dados_venda)

[['Lucas' 'Bia' 'Jean' 'Gabi' 'Pedro']
 ['150000' '230000' '82000' '143000' '184000']]


In [ ]:
dados_venda.dtype

dtype('<U11')

### Podemos buscar elementos em um array

In [ ]:
dados_venda

array([['Lucas', 'Bia', 'Jean', 'Gabi', 'Pedro'],
       ['150000', '230000', '82000', '143000', '184000']], dtype='<U11')

In [ ]:
# Buscando a primeira linha (lembrando que o Python começa no 0)
dados_venda[0]

array(['Lucas', 'Bia', 'Jean', 'Gabi', 'Pedro'], dtype='<U11')

In [ ]:
# BUscando na primeira linha, a segunda coluna
dados_venda[0][1]

'Bia'

In [ ]:
dados_venda[1][2]

'82000'

### Também podemos mostrar as informações estatísticas de um array

In [ ]:
# Mostrando as informações estatísticas dessa matriz
dados_venda = np.array([[150000,230000,82000,143000,184000],[5,8,8,5,12]])

**Média do array:** <br>
<font color="blue">**np.mean(**</font>meu_array<font color="blue">**)**</font>

In [ ]:
# Média da primeira linha
np.mean(dados_venda[0])

157800.0

In [ ]:
# Média da segunda linha
np.mean(dados_venda[1])

7.6

**Mediana:** <br>
<font color="blue">**np.median(**</font>meu_array<font color="blue">**)**</font>

In [ ]:
# Mediana da primeira linha
np.median(dados_venda[0])

150000.0

**Desvio Padrão:** <br>
<font color="blue">**np.std(**</font>meu_array<font color="blue">**)**</font>

In [ ]:
# Desvio padrão da primeira linha
np.std(dados_venda[0])

48836.05225650411

### E realizar operações aritméticas, agregação, comparação, mínimo e máximo, etc

In [ ]:
# Considerando esses 2 arrays
array1 = np.array([1,2,3,4,5])
array2 = np.array([7,8,9,10,11])

In [ ]:
# Soma
array1 + array2

array([ 8, 10, 12, 14, 16])

In [ ]:
# Multiplicação por um valor
array1 * 2

array([ 2,  4,  6,  8, 10])

In [ ]:
# Multiplicação de arrays
array1 * array2

array([ 7, 16, 27, 40, 55])

In [ ]:
# Potência
np.power(array2,array1)

array([     7,     64,    729,  10000, 161051])

In [ ]:
# Soma dos valores da primeira linha
np.sum(array1)

15

In [ ]:
# Soma acumulada dos valores da primeira linha
np.cumsum(array1)

array([ 1,  3,  6, 10, 15])

In [ ]:
# Valor mínimo
array1.min()

1

In [ ]:
# Valor máximo
array1.max()

5

### <font color="blue">**Tudo isso, vamos relembrar ao falar do Pandas**</font>

### Mais sobre NumPy
- Também podemos usar o NumPy para criar arrays de valores constantes, criar tipos específicos de matrizes (como matriz identidade), fazer produto matricial, transposta, etc
- Não vamos focar nisso agora para podermos aprofundar no pandas