# O NumPy
- https://numpy.org/doc/stable/index.html

### O array no numpy
- https://numpy.org/doc/stable/user/quickstart.html

In [120]:
# Importando o numpy
import numpy as np

In [121]:
a = np.arange(15).reshape(3, 5) # reshape coloca os dados em linhas e colunas
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [122]:
b = np.array([[1,2,3],[4,5,6]])

In [123]:
# Verificando a dimensão desse array
a.ndim

2

In [124]:
# Verificando a forma do array
a.shape

(3, 5)

In [125]:
# Verificando o tipo dos dados
b.dtype

dtype('int32')

### Qual a diferença de uma lista para um array?
- https://numpy.org/doc/stable/user/absolute_beginners.html#whats-the-difference-between-a-python-list-and-a-numpy-array
- Definição do próprio NumPy:
    - As matrizes NumPy são mais rápidas e compactas do que as listas do Python. Uma matriz consome menos memória e é conveniente de usar. O NumPy usa muito menos memória para armazenar dados e fornece um mecanismo para especificar os tipos de dados. Isso permite que o código seja otimizado ainda mais.
    - O NumPy oferece uma enorme variedade de maneiras rápidas e eficientes de criar matrizes e manipular dados numéricos dentro delas. Embora uma lista Python possa conter diferentes tipos de dados em uma única lista, todos os elementos em uma matriz NumPy devem ser homogêneos. As operações matemáticas que devem ser executadas em arrays seriam extremamente ineficientes se os arrays não fossem homogêneos.

### Manipulando arrays

**Criando um array básico**
- https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-create-a-basic-array

In [126]:
# Criando um array com os valores 1,2 e 3
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([1, 2, 3, 4.5, 5])
array3 = np.array([1, 2, 3, '4', 5])

In [127]:
# verificando o tipo do array

array1.dtype

dtype('int32')

In [128]:
array2.dtype

dtype('float64')

In [129]:
array3.dtype

dtype('<U11')

In [130]:
# Array de zeros
np.zeros(2)

array([0., 0.])

In [131]:
# Array de valores 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [132]:
# Array com um intervalo de valores
np.arange(4)

array([0, 1, 2, 3])

In [133]:
# Adicionando um intervalo para o array
np.arange(5,9)

array([5, 6, 7, 8])

In [134]:
# Adicionando um "passo" para o array
np.arange(20,6,-1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7])

In [135]:
# Utilizando o linspace para criar esse array
np.linspace(16, 21, num=5)

array([16.  , 17.25, 18.5 , 19.75, 21.  ])

### Buscando elementos no array
- https://numpy.org/doc/stable/user/absolute_beginners.html#indexing-and-slicing

In [136]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [137]:
# Buscando a primeira linha
a[0]

array([0, 1, 2, 3, 4])

In [138]:
# Na primeira linha, buscando o elemento de índice 3
a[0][3]

3

In [139]:
# Buscando os elementos de índice 1 a 3 (incluindo o 3) na primeira linha
a[0][1:4]

array([1, 2, 3])

In [140]:
# Buscando apenas os valores maiores que 5
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [141]:
# Buscando valores maiores que 5 E (&) menores que 11
novo_array = a[(a>5) & (a<11)]

In [142]:
novo_array

array([ 6,  7,  8,  9, 10])

### Operações básicas no array
- https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations

In [143]:
b = np.arange(6).reshape(2, 3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [144]:
# Somando todos os valores
b.sum()

15

In [145]:
# Somando apenas os valores da linha
b.sum(axis=1)

array([ 3, 12])

In [146]:
# Somando apenas os valores da coluna
b.sum(axis=0)

array([3, 5, 7])

In [151]:
# fazendo a soma acumulada desses valores

b.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12]])

In [147]:
# Somando 1 em todos os valores
b+1

array([[1, 2, 3],
       [4, 5, 6]])

In [148]:
# Multiplicando 2 em todos os valores do array
b*2

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [149]:
# Verificando o menor valor desse array
b.min()

0

In [152]:
# Verificando o menor valor desse array por linha
b.min(axis=1)

array([0, 3])

In [150]:
# E agora o maior valor
b.max()

5

In [153]:
# média

b.mean()

2.5

In [155]:
# média da primeira linha
b[0].mean()

1.0

In [156]:
# média da segunda linha
b[1].mean()

4.0

In [157]:
# calculando mediana
np.median(b)

2.5